name = "BioSymbols"
uuid = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "5.1.4"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.10"
PrecompileTools = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
