# Project information
site_name:   BioSymbols.jl
site_description: Bioloigcal symbol types for Julia
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/BioSymbols.jl/

# Repository
repo_url:  https://github.com/BioJulia/BioSymbols.jl

# Copyright
copyright: Copyright (c) 2017 The BioJulia Organisation

# Documentation and theme
theme: biojulia
docs_dir: 'build'

# Options
extra:
  logo: images/logo.png
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
- Introduction: index.md
- NucleicAcids: types.md
